### ISSUE TITLE
Why model is not fit in the script?

### ISSUE THREAD

**Issue by yashkan27** [ksjagtap/QuantConnect-Trading-Strategies#1]
I was looking at your script for getting the better understanding of the platform and model deployment. I notice that you created the LSTM model, compile the model but when it comes to the model training part all the instances where `model.fit` is present you commented that line.
Can you help me in understanding this?

**Comment by ksjagtap** [comment]
Hi Yashkan, thanks for the feedback. You are right, it needs to be uncommented when you run it on your end. 

In my case, I had run it and arrived at the optimal parameters opt_cells = 200 and opt_epochs = 100, hence to prevent it from always fitting during testing and taking up time, I commented it out. If I wanted to rerun now, I would need to uncomment it too!
